import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import './globals.scss';

import Navbar from "./(root)/_components/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Portfolio | Muhammad Furqan Latif",
  description: "Generated by create next app",
   icons: {
    icon: '/assets/images/portfolio_Favicon.png',
    shortcut: '/assets/images/portfolio_Favicon.png',
    apple: '/assets/images/portfolio_Favicon.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Navbar />
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {children}
        </body>
      </html>
    </>
  );
}
